name: Daily Python Script Run

on:
  schedule:
    - cron: '30 16 * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies (if any)
      - name: Install Dependencies
        run: |
          pip install -r dependencies.txt

      # Run the Python scripts
      - name: Run Python Scripts
        run: |
          python "Golden Cross Finder.py"
          python "Drop Cross Finder.py"
          python "CSV Manager.py"
          python "Email Sender.py"
